bot:
  application_id: "1206364463079628862"
  alert_channel_id: "1261531470930116712"
  log_level: "debug"
  alerts: false

ranna:
  endpoint: "http://localhost:8080"
#  version: ""
#  user_agent: ""
