bot:
  application_id: 1206364463079628862
  alert_channel_id: 1261531470930116712
  alerts: false
  intents:
    - guilds
    - guild_members
    - guild_bans
    - guild_presences
    - guild_messages
    - message_content

logger:
  level: debug
  outfile:
  format:

ranna:
  endpoint: http://localhost:8080
  version:
  user_agent: OverlordDevelopment/1.0
