services:

  overlord:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: overlord_bot
    depends_on:
      - postgres
    restart: on-failure:3
    env_file: .docker.env
    volumes:
      - ./config.docker.yaml:/app/config.yaml

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: discord_server_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ranna:
    image: "ghcr.io/ranna-go/ranna:latest"
    container_name: ranna
    environment:
      HOSTROOTDIR: "/var/opt/ranna"
      API.MAXOUTPUTLEN: "1M"
      SANDBOX.MEMORY: "50M"
      SANDBOX.TIMEOUTSECONDS: "20"
      SANDBOX.STREAMBUFFERCAP: "1M"
      RANNA_DEBUG: true
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/opt/ranna:/var/opt/ranna"
    restart: on-failure:3

volumes:
  postgres_data: