services:

  overlord:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BOT_TOKEN: ${BOT_TOKEN}
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    container_name: overlord_bot
    environment:
      MIGRATION_DB_URL: postgres://root:password@postgres:5432/discord_server_management?sslmode=disable
      OVERLORD_DB_URL: postgres://overlord_bot:password@postgres:5432/discord_server_management?sslmode=disable

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: discord_server_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ranna:
    image: "ghcr.io/ranna-go/ranna:latest"
    container_name: ranna
    environment:
      HOSTROOTDIR: "/var/opt/ranna"
      API.MAXOUTPUTLEN: "1M"
      SANDBOX.MEMORY: "50M"
      SANDBOX.TIMEOUTSECONDS: "20"
      SANDBOX.STREAMBUFFERCAP: "1M"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/opt/ranna:/var/opt/ranna"
    ports:
      - "8080:8080"
    restart: "on-failure"

volumes:
  postgres_data: