name: Publish Image to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build Binary
        run: env GOOS=linux CGO_ENABLED=0 go build -o ./bin/discord-bot .

      - name: Archive Binary
        uses: actions/upload-artifact@v2
        with:
          name: discord-bot
          path: ./bin/discord-bot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Binary Artifact
        uses: actions/download-artifact@v2
        with:
          name: discord-bot
          path: ./bin/discord-bot

      - name: Build Docker Image
        run: docker build --progress=plain -t zachsampson/discord-bot:latest .

      - name: Publish Docker Image
        run: |
          docker login -u zachsampson -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zachsampson/discord-bot:latest
